// Reads the Vite-built web app (web-dist/) and writes src/generated/assets.ts
// embedding every file as base64 — so adminUI() can serve the whole bundle
// with zero filesystem access at runtime, working the same in Node, Workers,
// and Bun. Run as part of `pnpm build`, after `vite build`.
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { extname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = fileURLToPath(new URL('..', import.meta.url))
const webDist = join(packageRoot, 'web-dist')
const outFile = join(packageRoot, 'src/generated/assets.ts')

const CONTENT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.map': 'application/json; charset=utf-8',
}

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(full)))
    else files.push(full)
  }
  return files
}

const files = await walk(webDist)
if (files.length === 0) {
  throw new Error(`embed-assets: no files found in ${webDist} — did \`vite build\` run first?`)
}

const entries = []
for (const file of files) {
  const key = relative(webDist, file).split('\\').join('/') // posix-style keys regardless of OS
  const contentType = CONTENT_TYPES[extname(file)] ?? 'application/octet-stream'
  const base64 = (await readFile(file)).toString('base64')
  entries.push(`  ${JSON.stringify(key)}: { contentType: ${JSON.stringify(contentType)}, base64: ${JSON.stringify(base64)} },`)
}

const contents = `// Generated by scripts/embed-assets.mjs — do not edit by hand.
export interface EmbeddedAsset {
  contentType: string
  /** Base64-encoded file contents. */
  base64: string
}

export const assets: Record<string, EmbeddedAsset> = {
${entries.join('\n')}
}
`

await writeFile(outFile, contents)
console.log(`embed-assets: wrote ${files.length} file(s) to ${relative(packageRoot, outFile)}`)
